config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  resources :homes
  resources :players
  resources :ring_games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chip.rb
class Chip < ApplicationRecord
end

app/models/chip_change.rb
class ChipChange < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/home_owner.rb
class HomeOwner < ApplicationRecord
end

app/models/home_player.rb
class HomePlayer < ApplicationRecord
end

app/models/home_ring_game.rb
class HomeRingGame < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :ring_game_players
  has_many :ring_games, through: :ring_game_players
end

app/models/player_chip.rb
class PlayerChip < ApplicationRecord
end

app/models/ring_game.rb
class RingGame < ApplicationRecord
  has_many :ring_game_players
  has_many :players, through: :ring_game_players
end

app/models/ring_game_player.rb
class RingGamePlayer < ApplicationRecord
  belongs_to :player
  belongs_to :ring_game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)

    if @home.save
      redirect_to @home
    else
      render :new
    end
  end

  def show
    @home = Home.find(params[:id])
  end

  def destroy
    home = Home.find(params[:id])
    home.destroy
    redirect_to homes_url
  end

  private

  def home_params
    params.require(:home).permit(:id, :name)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :set_player, only: %w(show edit update destroy)

  def index
    @players = Player.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      respond_to do |format|
        format.html { redirect_to players_url, notice: 'Player was successfully created.' }
      end
    else
      format.html { render :new }
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to players_url, notice: 'Player was successfully updated.' }
      end
    end
  end

  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
    end
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/controllers/ring_games_controller.rb
class RingGamesController < ApplicationController

  before_action :set_ring_game, only: %w(show edit udpate destroy)

  def new
    @players = Player.all
    @ring_game = RingGame.new
  end

  def create
    @ring_game = RingGame.new(ring_game_params)

    if @ring_game.save
      respond_to do |format|
        format.html { redirect_to @ring_game }
      end
    else
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def show
    @players = @ring_game.players
  end

  def edit
  end

  def update
    @ring_game.update
  end

  def destroy
  end

  private

  def set_ring_game
    @ring_game = RingGame.find(params[:id])
  end

  def ring_game_params
    params.require(:ring_game).permit(:blind, :starting_stack, player_ids: []).merge(number_of_times: get_number_of_times)
  end

  def get_number_of_times
    just_before = RingGame.last
    return 1 if just_before.nil?
    if reset_count?(just_before.created_at)
      number_of_times_per_day = 1
    else
      number_of_times_per_day = just_before.number_of_times + 1
    end
    number_of_times_per_day
  end

  def time_now
    Time.current
  end

  def reset_count?(just_before_date)
    return true if just_before_date.nil?
    now = time_now
    now > six_am_on_today && just_before_date < six_am_on_today
  end

  def six_am_on_today
    time_now.beginning_of_day + 6.hour
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/ring_games_helper.rb
module RingGamesHelper
  def starting_stack_as_bb
    as_bb = @ring_game.starting_stack / @ring_game.blind
    "#{as_bb}BB (#{@ring_game.starting_stack})"
  end
end

app/views/homes/new.html.slim
h1 Home作成

= form_with model: @home, local: true do |form|
    = form.text_field :name
    = form.submit '作成する'

app/views/homes/show.html.slim
h1 = @home.name

= link_to '削除する', home_path(@home), method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title Aces
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

.top-page
  .header
    h1 Aces
  .content
    .content-right
      ul
        li
          = link_to 'Profile', players_path(@player)
        li
          = link_to 'Home'
    .content-main
      body
        = yield

app/views/players/_form.html.slim
= form_for(@player) do |f|
  = f.label :name
  = f.text_field :name
  = f.submit btn_text

app/views/players/edit.html.slim
h1 Player
= render partial: 'form', locals: { btn_text: "Update" }

app/views/players/index.html.slim
h1 Players
= link_to 'New', new_player_path

table
  - @players.each do |player|
    tr
      th = player.name
      td = link_to 'Edit', edit_player_path(player)
      td = link_to 'Destroy', player_path(player), method: :delete, data: { confirm: 'Are you sure?' }

app/views/players/new.html.slim
h1 Player
= render partial: 'form', locals: { btn_text: "Add" }

app/views/players/show.html.slim
h1 Player
= @player.name

app/views/ring_games/index.html.slim
h1 RingGame

= link_to 'New Game', new_ring_game_path

app/views/ring_games/new.html.slim
h1 RingGame

= form_with(model: @ring_game) do |f|
  = f.label :blind
  = f.text_field :blind
  = f.label :starting_stack
  = f.text_field :starting_stack
  = f.collection_check_boxes(:player_ids, @players, :id, :name, local: true) do |p|
    = p.label do
      div
        = p.check_box
        = p.text

  = f.submit 'Start'

app/views/ring_games/show.html.slim
h1 RingGame

h2 Players

- @players.each do |player|
  p = player.name

h2 Blind
p = @ring_game.blind

h2 Starting Stack
p = starting_stack_as_bb